//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLogReader.Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_logging
    {
        public System.Guid system_logging_guid { get; set; }
        public Nullable<System.DateTime> entered_date { get; set; }
        public string log_application { get; set; }
        public string log_date { get; set; }
        public string log_level { get; set; }
        public string log_logger { get; set; }
        public string log_message { get; set; }
        public string log_machine_name { get; set; }
        public string log_user_name { get; set; }
        public string log_call_site { get; set; }
        public string log_thread { get; set; }
        public string log_exception { get; set; }
        public string log_stacktrace { get; set; }
        public string aspnet_sessionid { get; set; }
    }
}
