const ActionTypes = {
  RECEIVE_RAW_LOG_ITEMS: 'RECEIVE_RAW_LOG_ITEMS',
  MERGE_RAW_LOG_ITEMS: 'MERGE_RAW_LOG_ITEMS',
  RECEIVE_CONFIG: 'RECEIVE_CONFIG',
  RECEIVE_RAW_HOURLY_LOG_COUNTS: 'RECEIVE_RAW_HOURLY_LOG_COUNTS',
  SET_SELECTED_ENVIRONMENT: 'SET_SELECTED_ENVIRONMENT',
  SET_SEARCH_APPLICATION: 'SET_SEARCH_APPLICATION',
  SET_SEARCH_MACHINE: 'SET_SEARCH_MACHINE',
  SHOW_SETTINGS: 'SHOW_SETTINGS',
  SHOW_HOME: 'SHOW_HOME',
};

export default ActionTypes;